name = "azure-stack"
location = "Central India"
vnetcidr = "192.168.0.0/16"
websubnetcidr = "192.168.1.0/24"
appsubnetcidr = "192.168.2.0/24"
dbsubnetcidr = "192.168.3.0/24"
web_host_name = "webserver"
web_username = "web_user"
web_os_password = "@Webuser1"
app_host_name = "appserver"
app_username = "app_user"
app_os_password = "@Appuser1"
primary_database = "sql-primary-database"
primary_database_admin = "sqladmin"
primary_database_password = "pa$$w0rd"
primary_database_version = "12.0"

